#!/bin/sh
# When configured within MPICH via PAC_CONFIG_SUBDIR, this file will be sourced
# by the top-level configure.  This lets us propagate shell variable changes
# back upstream.

CPPFLAGS="  -I/jet/home/rongon/mpi/mvapich/mvapich2-2.3.2/src/mpl/include -I/jet/home/rongon/mpi/mvapich/mvapich2-2.3.2/src/mpl/include -I/jet/home/rongon/mpi/mvapich/mvapich2-2.3.2/src/openpa/src -I/jet/home/rongon/mpi/mvapich/mvapich2-2.3.2/src/openpa/src -D_REENTRANT -I/jet/home/rongon/mpi/mvapich/mvapich2-2.3.2/src/mpi/romio/include -I/include -I/include -I/include -I/include"
WRAPPER_LIBS="$WRAPPER_LIBS "
